[".config/fish/functions/fisher.fish"]
    type = "file"
    url = "https://git.io/fisher"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"

[".config/base16-shell"]
    type = "git-repo"
    url = "https://github.com/chriskempson/base16-shell.git"
    refreshPeriod = "168h"

[".fzf"]
    type = "git-repo"
    url = "https://github.com/junegunn/fzf.git"
    refreshPeriod = "168h"
    [".fzf".clone]
        args = ["--depth", "1"]
    [".fzf".pull]
        args = ["--ff-only"] 