# --- TOML ---
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "go"
language-servers = ["gopls", "golangci"]
formatter = { command = "gofumpt" }

[[language]]
name = "python"
formatter = { command = "ruff format"
auto-format = true

# --- C# via csharp-ls (.NET 8) ---
[[language]]
name = "c-sharp"
language-servers = ["csharp-ls"]
formatter = { command = "csharpier", args = ["--write-stdout"] }
