# btop config

# Use 24-bit truecolor
truecolor = True

# Update time in milliseconds (2000ms = 2 seconds)
update_ms = 2000

# Processes sorting: "cpu lazy" is easier to follow than "cpu direct"
proc_sorting = "cpu lazy"

# Show processes as a tree
proc_tree = False

# Use a darkening gradient in the process list
proc_gradient = True

# Show cpu graph for each process
proc_cpu_graphs = True

# Shows the system uptime in the CPU box
show_uptime = True

# Show cpu temperature
check_temp = True

# Show battery stats if battery is present
show_battery = True

# Rounded corners on boxes
rounded_corners = True

# Default graph symbol ("braille" offers highest resolution)
graph_symbol = "braille"

# Draw a clock at top of screen
clock_format = "%X"

# Log level
log_level = "WARNING"
